apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: webhook-notifapp
spec:
  serviceAccountName: pipeline
  triggers:
    - triggerRef: webhook-notifapp-pr-merged

---

apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: el-webhook-notifapp
  annotations:
    cert-manager.io/issuer-name: letsencrypt-http
    cert-manager.io/issuer-kind: ClusterIssuer
    cert-manager.io/common-name: "webhook-notifapp-pipeline.rellomine.ru"
    cert-manager.io/subject-organizations: "ReLLoMine"
spec:
  host: webhook-notifapp-pipeline.rellomine.ru
  to:
    kind: Service
    name: el-webhook-notifapp
  port:
    targetPort: http-listener