apiVersion: triggers.tekton.dev/v1beta1
kind: Trigger
metadata:
  name: webhook-notifapp-pr-merged
spec:
  serviceAccountName: pipeline
  interceptors:
    - ref:
        name: "github"
      params:
        - name: "secretRef"
          value:
            secretName: github-secret
            secretKey: secretToken
        - name: "eventTypes"
          value: ["pull_request"]
    - ref:
        name: "cel"
      params:
        - name: "filter"
          value: >
            body.action == 'closed' &&
            body.pull_request.merged == true &&
            body.pull_request.base.ref == 'master'
        - name: "overlays"
          value:
            - key: repository_name
              expression: "body.repository.name.lowerAscii()"
  bindings:
    - ref: webhook-notifapp
  template:
    ref: webhook-notifapp

---
apiVersion: v1
kind: Secret
metadata:
  name: github-secret
type: Opaque
stringData:
  secretToken: "e4131c063286e1d706779b0c8d5c6367"